devicemap = {
    'a700': 'Acer Iconia A700',
    'ace': 'HTC Desire HD / Inspire 4G',
    'anzu': 'SE XperiaArc-LT15i',
    'aoba': 'SE XperiaIon-LT28h',
    'blade': 'ZTE Blade',
    'bravoc': 'HTC Desire CDMA',
    'bravo': 'HTC Desire',
    'buzz': 'HTC Wildfire',
    'c660': 'LG Optimus Pro',
    'captivatemtd': 'Samsung Captivate',
    'click': 'HTC Tattoo',
    'coconut': 'SE LiveWithWalkman-WT19i',
    'cooper': 'Samsung Galaxy Ace',
    'crespo4g': 'Google Nexus S 4G',
    'crespo': 'Google Nexus S',
    'd2att': 'Samsung Galaxy S III (AT&T)',
    'd2cri': 'Samsung Galaxy S III (Cricket)',
    'd2mtr': 'Samsung Galaxy S III (M. PCS)',
    'd2spr': 'Samsung Galaxy S III (Sprint)',
    'd2tmo': 'Samsung Galaxy S III (TMUS)',
    'd2usc': 'Samsung Galaxy S III (US Cell)',
    'd2vzw': 'Samsung Galaxy S III (vzw)',
    'desirec': 'Droid Eris',
    'doubleshot': 'HTC Doubleshot / TMo MT4GS',
    'dream_sapphire': 'HTC Dream / Magic',
    'droid2': 'Motorola DROID2',
    'droid2we': 'Motorola DROID2 World Edition',
    'e400': 'LG Optimus L3',
    'e510': 'LG Optimus Hub',
    'e720': 'LG Optimus Chic',
    'e730': 'LG Optimus Sol',
    'e739': 'T-Mobile LG myTouch',
    'encore': 'Barnes&Noble Nook Color',
    'endeavoru': 'HTC One X',
    'epicmtd': 'Samsung Epic 4G',
    'espresso': 'HTC myTouch 3G Slide',
    'everest': 'Motorola Xoom (3G)',
    'evita': 'HTC One XL',
    'fascinatemtd': 'Samsung Fascinate',
    'fireball': 'HTC Incredible 4G',
    'galaxys2att': 'Samsung Galaxy S2 ATT',
    'galaxys2': 'Samsung Galaxy S2',
    'galaxysbmtd': 'Samsung Galaxy S (B)',
    'galaxysmtd': 'Samsung Galaxy S',
    'glacier': 'T-Mobile myTouch 4G / HTC Glacier',
    'grouper': 'Google Nexus 7 (wifi)',
    'hallon': 'SE XperiaNeo-MT15i',
    'hercules': 'Samsung Galaxy S2 T-Mobile',
    'heroc': 'HTC Hero CDMA',
    'hero': 'HTC Hero',
    'i727': 'Samsung Galaxy S2 ATT LTE',
    'i777': 'Samsung Galaxy S2 ATT',
    'i9100': 'Samsung Galaxy S II (intl)',
    'i9100g': 'Samsung Galaxy S II (G)',
    'i9300': 'Samsung Galaxy S III (intl)',
    'inc': 'Droid Incredible',
    'iyokan': 'SE XperiaPro-MK16i',
    'jewel': 'HTC Evo 4G LTE',
    'jordan': 'Motorola Defy',
    'jordan_plus': 'Motorola Defy+',
    'legend': 'HTC Legend',
    'liberty': 'HTC Aria',
    'maguro': 'Google Galaxy Nexus (GSM)',
    'mako': 'Google Nexus 4',
    'mango': 'SE XperiaMiniPro-SK17i',
    'manta': 'Google Nexus 10',
    'mesmerizemtd': 'Samsung Mesmerize',
    'mint': 'Sony Xperia T',
    'morrison': 'Motorola Cliq',
    'motus': 'Motorola Backflip',
    'n7000': 'Samsung Galaxy Note (intl)',
    'n7100': 'Samsung Galaxy Note 2',
    'n8000': 'Samsung Galaxy Note 10 (GSM)',
    'n8013': 'Samsung Galaxy Note 10 (wifi)',
    'nozomi': 'Sony Xperia S',
    'odroidu2': 'Hardkernel ODROID-U2',
    'olympus': 'Motorola Atrix',
    'one': 'Geeksphone ONE',
    'p1': 'Samsung Galaxy Tab',
    'p1c': 'Samsung Galaxy Tab (CDMA)',
    'p3': 'Samsung Galaxy Tab 10.1v',
    'p3100': 'Samsung Galaxy Tab2 7',
    'p3110': 'Samsung Galaxy Tab2 7 (Wifi)',
    'p350': 'LG Optimus Me',
    'p4': 'Samsung Galaxy Tab 10.1',
    'p4wifi': 'Samsung Galaxy Tab 10.1 (Wifi)',
    'p4tmo': 'Samsung Galaxy Tab 10.1 (TMUS)',
    'p4vzw': 'Samsung Galaxy Tab 10.1 (vzw)',
    'p5': 'Samsung Galaxy Tab 8.9 (3G)',
    'p500': 'LG Optimus One',
    'p5100': 'Samsung Galaxy Tab2 10.1',
    'p5110': 'Samsung Galaxy Tab2 10.1 (Wifi)',
    'p5wifi': 'Samsung Galaxy Tab 8.9 (Wifi)',
    'p720': 'LG Optimus 3D Max',
    'p920': 'LG Optimus 3D',
    'p925': 'LG ATT Thrill',
    'p930': 'LG Nitro HD / Optimus LTE',
    'p970': 'LG Optimus Black',
    'p990': 'LG Optimus 2X',
    'p999': 'T-Mobile G2x',
    'passion': 'Google Nexus One',
    'pyramid': 'HTC Sensation',
    'quincyatt': 'Samsung Galaxy Note (AT&T)',
    'quincytmo': 'Samsung Galaxy Note (TMUS)',
    'ruby': 'HTC Amaze',
    's5670': 'Samsung Galaxy Fit',
    'saga': 'HTC Desire S',
    'satsuma': 'SE XperiaActive-ST17i',
    'shadow': 'Motorola Droid X',
    'shakira': 'SE Xperia X8-E15i',
    'sholes': 'Motorola Droid',
    'showcasemtd': 'Samsung Showcase',
    'skate': 'ZTE Skate',
    'skyrocket': 'Samsung Galaxy S2 ATT LTE',
    'smultron': 'SE XperiaMini-ST15i',
    'speedy': 'HTC Evo Shift',
    'su640': 'LG Optimus LTE (SKT)',
    'sunfire': 'Motorola Photon',
    'supersonic': 'HTC Evo',
    'steelhead': 'Google Nexus Q',
    'stingray': 'Motorola Xoom (vzw)',
    't769': 'Samsung Galaxy S Blaze 4G',
    'tass': 'Samsung Galaxy Mini',
    'tenderloin': 'HP Touchpad',
    'tf101': 'ASUS EeePad Transformer',
    'tf201': 'ASUS EeePad Transformer Prime',
    'tf300t': 'ASUS Transformer Pad',
    'tf700t': 'ASUS Transformer Pad Infinity',
    'tilapia': 'Google Nexus 7 (GSM)',
    'toro': 'Samsung Galaxy Nexus (vzw)',
    'toroplus': 'Samsung Galaxy Nexus (sprint)',
    'u8150': 'Huawei U8150',
    'u8160': 'Huawei U8160',
    'u8220': 'Huawei U8220',
    'urushi': 'SE XperiaRay-ST18i',
    'v9': 'ZTE V9',
    'vega': 'Advent Vega',
    'vibrantmtd': 'Samsung Vibrant',
    'ville': 'HTC One S',
    'vision': 'T-Mobile G2 / HTC Desire Z',
    'vivo': 'Droid Incredible S',
    'vivow': 'HTC Incredible 2',
    'vs920': 'LG Spectrum',
    'wingray': 'Motorola Xoom (Wifi)',
    'zeppelin': 'Motorola CliqXT',
    'zero': 'Geeksphone ZERO',
    'zeusc': 'SE Xperia Play CDMA-R800x',
    'zeus': 'SE Xperia Play -R800i'
}
