devicemap = {
    'a700': 'Acer Iconia Tab A700',
    'acclaim': 'Barnes & Noble Nook Table',
    'ace': 'HTC Desire HD / Inspire 4G',
    'anzu': 'Sony Ericsson Xperia Arc',
    'aoba': 'Sony Xperia ion',
    'betelgeuse': 'Toshiba Folio 100',
    'blade': 'ZTE Blade',
    'blade2_p736e': 'ZTE Crescent (TMO)',
    'blade2_p736v': 'ZTE Crescent (OUK)',
    'bravo': 'HTC Desire (GSM)',
    'bravoc': 'HTC Desire (CDMA)',
    'buzz': 'HTC Wildfire',
    'c660': 'LG Optimus Pro',
    'c800': 'LG myTouch Q',
    'captivatemtd': 'Samsung Captivate',
    'click': 'HTC Tattoo',
    'coconut': 'Sony Ericsson Live with Walkman',
    'cooper': 'Samsung Galaxy Ace',
    'crespo': 'Google Nexus S',
    'crespo4g': 'Google Nexus S 4G',
    'd2att': 'Samsung Galaxy S III (AT&T)',
    'd2cri': 'Samsung Galaxy S III (Cricket)',
    'd2mtr': 'Samsung Galaxy S III (MetroPCS)',
    'd2spr': 'Samsung Galaxy S III (Sprint)',
    'd2tmo': 'Samsung Galaxy S III (T-Mobile)',
    'd2usc': 'Samsung Galaxy S III (US Cellular)',
    'd2vzw': 'Samsung Galaxy S III (Verizon)',
    'desirec': 'Droid Eris',
    'doubleshot': 'T-Mobile myTouch 4G Slide',
    'dream_sapphire': 'HTC Dream / Magic',
    'droid2': 'Motorola Droid 2',
    'droid2we': 'Motorola Droid 2 Global',
    'e400': 'LG Optimus L3',
    'e510': 'LG Optimus Hub',
    'e610': 'LG Optimus L5',
    'e720': 'LG Optimus Chic',
    'e730': 'LG Optimus Sol',
    'e739': 'LG myTouch',
    'e975': 'LG Optimus G (Intl)',
    'edison': 'Motorola Atrix 2',
    'encore': 'Barnes & Noble Nook Color',
    'endeavoru': 'HTC One X',
    'epicmtd': 'Samsung Epic 4G',
    'es209ra': 'Sony Ericsson Xperia X10',
    'espresso': 'T-Mobile myTouch 3G Slide',
    'everest': 'Motorola Xoom (GSM)',
    'evita': 'HTC One XL',
    'fascinatemtd': 'Samsung Fascinate',
    'find5': 'Oppo Find 5',
    'fireball': 'Droid Incredible 4G LTE',
    'galaxys2att': 'Samsung Galaxy S II (AT&T)',
    'galaxys2': 'Samsung Galaxy S II (Intl)',
    'galaxysbmtd': 'Samsung Galaxy S (B)',
    'galaxysmtd': 'Samsung Galaxy S',
    'glacier': 'T-Mobile myTouch 4G',
    'grouper': 'Google Nexus 7 (Wi-Fi)',
    'haida': 'Sony Ericsson Xperia Neo V',
    'hallon': 'Sony Ericsson Xperia Neo',
    'hayabusa': 'Sony Xperia TX',
    'hercules': 'Samsung Galaxy S II (T-Mobile)',
    'hero': 'HTC Hero (GSM)',
    'heroc': 'HTC Hero (CDMA)',
    'hikari': 'Sony Xperia arco S',
    'holiday': 'HTC Raider 4G',
    'huashan': 'Sony Xperia SP',
    'i605': 'Samsung Galaxy Note II (Verizon)',
    'i777': 'Samsung Galaxy S II (AT&T)',
    'i9100': 'Samsung Galaxy S II (Intl)',
    'i9100g': 'Samsung Galaxy S II (G)',
    'i9103': 'Samsung Galaxy R',
    'i9300': 'Samsung Galaxy S III (Intl)',
    'i9305': 'Samsung Galaxy S III (GSM LTE)',
    'inc': 'Droid Incredible',
    'iyokan': 'Sony Ericsson Xperia Pro',
    'jem': 'Amazon Kindle Fire HD 8.9"',
    'jewel': 'HTC Evo 4G LTE',
    'jlo': 'Sony Xperia J',
    'jordan': 'Motorola Defy',
    'jordan_plus': 'Motorola Defy+',
    'l900': 'Samsung Galaxy Note II (Sprint)',
    'legend': 'HTC Legend',
    'liberty': 'HTC Aria',
    'maguro': 'Google Galaxy Nexus (GSM)',
    'mako': 'Google Nexus 4',
    'mango': 'Sony Ericsson Xperia Mini Pro',
    'manta': 'Google Nexus 10',
    'maserati': 'Motorola Droid 4',
    'mesmerizemtd': 'Samsung Mesmerize',
    'mesona': 'Sony Xperia miro',
    'mimmi': 'Sony Ericsson Xperia X10 Mini Pro',
    'mint': 'Sony Xperia T',
    'morrison': 'Motorola Cliq',
    'motus': 'Motorola Backflip',
    'n7000': 'Samsung Galaxy Note (Intl)',
    'n7100': 'Samsung Galaxy Note II (GSM Non-LTE)',
    'n8000': 'Samsung Galaxy Note 10.1 (GSM)',
    'n8013': 'Samsung Galaxy Note 10.1 (Wi-Fi)',
    'nanhu': 'Sony Xperia E',
    'nozomi': 'Sony Xperia S',
    'odin': 'Sony Xperia ZL',
    'odroidu2': 'Hardkernel ODROID-U2',
    'olympus': 'Motorola Atrix 4G',
    'one': 'Geeksphone One',
    'otter': 'Amazon Kindle Fire (1st gen)',
    'otter2': 'Amazon Kindle Fire (2nd gen)"',
    'p1': 'Samsung Galaxy Tab (GSM)',
    'p1c': 'Samsung Galaxy Tab (CDMA)',
    'p1l': 'Samsung Galaxy Tab (P1000L)',
    'p1n': 'Samsung Galaxy Tab (P1000N)',
    'p3': 'Samsung Galaxy Tab 10.1v',
    'p3100': 'Samsung Galaxy Tab 2 7.0 (GSM)',
    'p3110': 'Samsung Galaxy Tab 2 7.0 (Wi-Fi)',
    'p3113': 'Samsung Galaxy Tab 2 7.0 (Wi-Fi+IR)',
    'p350': 'LG Optimus Me',
    'p4': 'Samsung Galaxy Tab 10.1 (GSM)',
    'p4tmo': 'Samsung Galaxy Tab 10.1 (T-Mobile)',
    'p4vzw': 'Samsung Galaxy Tab 10.1 (Verizon)',
    'p4wifi': 'Samsung Galaxy Tab 10.1 (Wi-Fi)',
    'p5': 'Samsung Galaxy Tab 8.9 (GSM)',
    'p500': 'LG Optimus One',
    'p5100': 'Samsung Galaxy Tab2 10.1 (GSM)',
    'p5110': 'Samsung Galaxy Tab2 10.1 (Wi-Fi)',
    'p5113': 'Samsung Galaxy Tab2 10.1 (Wi-Fi+IR)',
    'p5wifi': 'Samsung Galaxy Tab 8.9 (Wi-Fi)',
    'p700': 'LG Optimus L7',
    'p720': 'LG Optimus 3D Max',
    'p760': 'LG Optimus L9',
    'p880': 'LG Optimus 4X HD',
    'p920': 'LG Optimus 3D',
    'p925': 'LG Thrill 4G',
    'p930': 'LG Nitro HD / Optimus LTE',
    'p970': 'LG Optimus Black',
    'p990': 'LG Optimus 2X',
    'p999': 'T-Mobile G2x',
    'passion': 'Google Nexus One',
    'pollux': 'Sony Xperia Tablet Z',
    'pyramid': 'HTC Sensation',
    'quincyatt': 'Samsung Galaxy Note (AT&T)',
    'quincytmo': 'Samsung Galaxy Note (T-Mobile)',
    'r950': 'Samsung Galaxy Note II (US Cellular)',
    'robyn': 'Sony Ericsson Xperia X10 Mini',
    'ruby': 'HTC Amaze 4G',
    's5670': 'Samsung Galaxy Fit',
    'saga': 'HTC Desire S',
    'satsuma': 'Sony Ericsson Xperia active',
    'scorpion_mini': 'Motorola Droid Razr M',
    'shadow': 'Motorola Droid X',
    'shakira': 'Sony Ericsson Xperia X8',
    'sholes': 'Motorola Droid',
    'shooteru': 'HTC Evo 3D (GSM)',
    'showcasemtd': 'Samsung Showcase',
    'skate': 'ZTE Skate',
    'skyrocket': 'Samsung Galaxy S II Skyrocket',
    'smb_a1002': 'ViewSonic G Tablet',
    'smultron': 'Sony Ericsson Xperia Mini',
    'solana': 'Motorola Droid 3',
    'speedy': 'HTC Evo Shift',
    'spyder': 'Motorola Droid Razr',
    'steelhead': 'Google Nexus Q',
    'stingray': 'Motorola Xoom (Verizon)',
    'su640': 'LG Optimus LTE (SK Telecom)',
    'sunfire': 'Motorola Photon',
    'supersonic': 'HTC Evo 4G',
    't0lteatt': 'Samsung Galaxy Note II (AT&T)',
    't0lte': 'Samsung Galaxy Note II (GSM LTE)',
    't0ltetmo': 'Samsung Galaxy Note II (T-Mobile)',
    't769': 'Samsung Galaxy S Blaze 4G',
    'taoshan': 'Sony Xperia L',
    'tapioca': 'Sony Xperia tipo',
    'targa': 'Motorola Droid Bionic',
    'tass': 'Samsung Galaxy Mini',
    'tate': 'Amazon Kindle Fire HD 7"',
    'tenderloin': 'HP Touchpad',
    'tf101': 'Asus Eee Pad Transformer',
    'tf201': 'Asus Eee Pad Transformer Prime',
    'tf300t': 'Asus Transformer Pad TF300T',
    'tf700t': 'Asus Transformer Pad Infinity',
    'tilapia': 'Google Nexus 7 (GSM)',
    'toro': 'Samsung Galaxy Nexus (Verizon)',
    'toroplus': 'Samsung Galaxy Nexus (Sprint)',
    'tsubasa': 'Sony Xperia V',
    'u8150': 'Huawei U8150',
    'u8160': 'Huawei U8160',
    'u8220': 'Huawei U8220',
    'u8815': 'Huawei Ascend G300',
    'umts_spyder': 'Motorola Razr',
    'urushi': 'Sony Ericsson Xperia Ray',
    'v9': 'ZTE V9',
    'vanquish': 'Motorola Droid Razr HD',
    'vega': 'Advent Vega',
    'vibrantmtd': 'Samsung Vibrant',
    'ville': 'HTC One S',
    'vision': 'T-Mobile G2 / HTC Desire Z',
    'vivo': 'Droid Incredible S',
    'vivow': 'HTC Incredible 2',
    'vs920': 'LG Spectrum',
    'wingray': 'Motorola Xoom (Wi-Fi)',
    'yuga': 'Sony Xperia Z',
    'z71': 'Commtiva Z71',
    'zeppelin': 'Motorola Cliq XT',
    'zero': 'Geeksphone Zero',
    'zeus': 'Sony Ericsson Xperia Play (GSM)',
    'zeusc': 'Sony Ericsson Xperia Play (CDMA)'
}
